services:
  - name: mp3mate-backend
    runtime: node
    region: oregon
    rootDir: server
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: PORT
        value: "10000"